apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-mysql-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-log-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: user-service-mysql
  labels:
    app: user-service-mysql
spec:
  selector:
    matchLabels:
      app: user-service-mysql
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user-service-mysql
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7.22
        name: mysql
        env:
        - name: MYSQL_USER
          value: clamor
        - name: MYSQL_DATABASE
          value: user
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: clamor-user-service-mysql-root-password
              key: value
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: clamor-user-service-mysql-password
              key: value
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: user-mysql-volume-claim
---
kind: Service
apiVersion: v1
metadata:
  name: user-service-mysql
spec:
  selector:
    app: user-service-mysql
  ports:
  - protocol: TCP
    port: 3306
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: ${DOCKER_REG}/clamor/user-service:latest
        imagePullPolicy: Always
        command: 
        - /user
        - serve
        ports:
        - containerPort: 80
        env:
        - name: BUILD_DATETIME
          value: "${DATETIME}"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: clamor-jwt-secret
              key: value
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: clamor-user-service-mysql-password
              key: value
        volumeMounts:
        - name: log-storage
          mountPath: /logs
      volumes:
      - name: log-storage
        persistentVolumeClaim:
          claimName: user-log-volume-claim
---
kind: Service
apiVersion: v1
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
  - protocol: TCP
    port: 80
---
